alecthomas/participle

_examples/ini/main.go
_examples/sql/main.go

A recent change in https://github.com/alecthomas/repr changed the
syntax of the repr.OmitEmpty() function to require an argument.  Two
examples call this function but were not updated to support the change.

Added arguments to repr.OmitEmpty() calls

---

parser.go

Participle was capable of converting strings to corresponding
types for int, float32, bool, etc.
This PR adds support for supporting those same convertions on
slice elements.
As such, the following grammar is now valid:
type Grammar struct {
Xs []int `{ @Number }`
}

Extend slice element type support.

---

nodes.go
parser.go
printer.go

add ebnf representation

---

lexer/text_scanner.go

https://golang.org/cl/161199 updated text/scanner error messages for
upcoming Go1.13.
Error message pre-1.13 contains "illegal char literal" while 1.13
changes it to "invalid char literal".
Fixes #50

participle/lexer: update error comparison to support Go1.13

---

_examples/sql/main.go

Hi, I'm making this example simplyer for my own purpose and found, that query like
```
SELECT xxx FROM (
SELECT * FROM zzz
WHERE attr_name = 'yyy' AND (attr_value_int = 0 OR attr_value_str = '0') AND (attr_value_bool = TRUE OR event_name IS NOT NULL)
GROUP BY uuid
)
WHERE date > '2019-05-20 06:01:06' AND date < '2019-05-22 00:00:00' AND event_id IN (42, 12)
LIMIT 100
```
with current data structure not handled conditions after 'OR', attr_value_str for example.

Fix type in go's structure for correct matching conditions

---

error.go
nodes.go
parser.go

Hi @alecthomas, I wanted to extract the expected token to help writing a more nuanced error reporting for my DSL. Would you be open to strongly typing this field?

Allow expected token in lexer error to be exported as a field.

---

parser.go

Hi @alecthomas, I have a use case where I wanted to build a parser with a mapper option like `participle.Unquote()`, but also gain access to the peeking lexer via `parser.ParseFromLexer`. I noticed that part of `participle.Build` a `mappingLexerDef` is constructed over the passed in lexer, but this is not an exported field so I'm not able to utilize the unquote mapper. Exposing the parser's via `(p *Parser) Lexer() lexer.Definition` will let me fulfill my usecase.
Example:
```go
parser = participle.MustBuild(&AST{}, participle.Lexer(myLexer), participle.Unquote())
lex, _ := parser.Lexer().Lex(reader)
peeker, _ := lexer.Upgrade(lex)
ast := &AST{}
err = parser.ParseFromLexer(peeker, ast)
```

Expose parser's built lexer

---

_examples/basic/eval.go

Due to a typo in the BASIC interpreter, it was mistakenly multiplying when the "/" was used.

Fix division on the BASIC interpreter

---

lexer/peek.go

When I get a lexer error, for example, an unterminated string, I still want to parse the tokens consumed so far into an AST. I'm using the AST to implement a LSP langserver, and I want to use the partial AST to continue syntax highlight the rest of the document.

Return peeking lexer on error to allow partial AST parsing

---

_examples/sql/main.go

Hey. Was playing with your awesome lib and noticed that. Specs: http://www.h2database.com/html/grammar.html#expression

Fix AND and OR precedence in SQL example

---

nodes.go
parser_test.go

While integrating your library into my project, I stumbled over an issue when I introduced custom types. One of them was of the kind `type MyBool bool`, and I received following error message:
value %!q(bool=true) is not correct type MyBool
I traced this down to somewhat strange behavior when comparing those types, at least if compared to how `type MyInt int` values are handled. I was able to reproduce this in test cases and provide a fix, but am not really sure whether my fix is the right way to fix the issue, I didn't really understand what's wrong here.
I think I'm at least correct on the test case showing unexpected behavior. I split into two commits, so you simply cherry-pick the test cases if you see a better way to fix this. At least I did not break any of the existing test cases. …

Custom bool type results in error message

---

lexer/peek.go

Hi @alecthomas, here with another use case. I'm not actually sure what's the best way to solve this so I'll first explain what I'm trying to do.
I'm using the peeking lexer to help write error reporting. Often I find myself wanting to know what is the cursor position of the unexpected token in the peeking lexer.
However, the peeking lexer counts in number of tokens, and the unexpected token only has its file position. And when the unexpected token error occurs, the token may be ahead or behind the cursor position 0. How do I reliable find the relative cursor position for this token?
My current solution is binary searching for it using the token's offset, but that requires exposes the peeking lexer's `Length()`:
```go
func searchToken(lex *lexer.PeekingLexer, tokenOffset int) (lexer.Token, …
```

Expose the length of tokens in the peeking lexer

---

README.md
grammar.go
nodes.go
parser_test.go
stringer.go

Here is a naive interpretation on how the negation could function.
If you want to do it entirely yourself, go ahead, but I'm willing to see this through as I really would like to see it come to fruition and this helps me hone my go funk.
I'm looking for some feedback on that preliminary implementation.
Am I missing something glaring ? Is the clone stuff potentially a performance killer ? Should Parse() be a little more involved ?

Starting work on negation, wip

---

lexer/stateful/stateful.go
lexer/stateful/stateful_test.go

fix backreference detection when \ is actually escaping another \

---

_examples/graphql/main.go
lexer/stateful/pattern.go
lexer/stateful/pattern_test.go
lexer/stateful/stateful.go
lexer/stateful/stateful_test.go

Runelookup to avoid testing regexps that have no chance to match

---

README.md
ebnf.go
ebnf_test.go
grammar.go
nodes.go
parser_test.go

Support for parser negative lookahead, i.e. a term saying the following expression cannot be matched. Works very much like existing negation, except it doesn't consume any tokens. Allows for example resolving grammar conflicts by blacklisting some keywords for a sub-expression about to be parsed. See the example in the tests to get the idea. Also explained in this issue: https://github.com/alecthomas/participle/issues/134

Add support for parser negative lookahead #134

---

grammar.go
grammar_test.go

See https://github.com/alecthomas/participle/issues/146 for explanation.
It seems there was just no reason for accepting `scanner.Char` (i.e. `':'`) as the token type specifier colon.

Fix treating a single-quoted colon string literal as token type specifier

---

README.md

This PR removes pinning the link to `cbe0cc62a3ad95955311002abd642f11543cb8ed` (which returns `Not found`).
The link is now fixed.
The line highlight `#` has also been updated.

Fix broken link to the GraphQL example in README

---

lexer/stateful/stateful.go
lexer/stateful/stateful_test.go

As mentioned [here](https://github.com/alecthomas/participle/discussions/157#discussioncomment-1035341), when porting certain grammars to Participle it may be necessary for the lexer to select the rule with the longest match, instead of the first rule that matches.
This behavior is added as the `MatchLongest()` lexer option.  The tests in the PR shows how this modifies the behavior.
Obviously the lexer is slower with this option enabled but I don't see a way around that.

Add the MatchLongest lexer option

---

README.md

- fixes #180
- make it clear custom lexers are fully supported
- indentation lexers are implementable
- stateful replaced regex
- EBNF lexer removed -- callers need to implement their own EBNF lexer
- reference #20 for indent lexer discussion

clarify README.md

---

parser.go
parser_test.go

This PR ensures that we correctly report the error returned from `Parse` when the grammar's root production implements `Parseable` & returns a non-nil, non-`NextMatch` error
Fixes #228

Report errors returned from root `Parseable`

---

README.md
options.go

Found some minor typos while reading the documentation.
I also fixed one error message, it was using the renamed function name ParseUnion.

fix documentation typos

---

README.md

Run the INI example from the README
```golang
type Value struct {
String *string  `  @String`
Number *float64 `| @Float`
}
...
ast := &INI{}
err := parser.ParseString("", "size = 10", ast)
// ast == &INI{
//   Properties: []*Property{
//     {Key: "size", Value: &Value{Number: &10}},
//   },
// }
```
```golang
Expected nil, but got: participle.UnexpectedTokenError{Unexpected:Token@1:8{-3, "10"}, at:(*participle.sequence)(0xc000026a80)}
```
Grammar states:
```golang
type Value struct {
String *string  `  @String`
Number *float64 `| @Float`
}
```
While the input data contains `@Int`, not `@Float`:
```golang
err = parser.ParseString("", "size = 10", ast)
```
So parsing ends with an error.
Change the Value definition as follows:
```golang
type Value struct {
String *string  `  @String`
Float …
```

fix INI parser example from README.md

---

cmd/participle/gen_lexer_cmd.go
lexer/internal/basiclexer.go

The generated struct name is now correct (uses name specified on command line) instead of using the name of the rule.
Tested that the generated lexer code now properly compiles without manual modification.

fix: proper generated struct name for state change

---

cmd/participle/gen_lexer_cmd.go
lexer/internal/conformance/conformance_test.go

@alecthomas - I wanted to get your feedback early on the approach to add a specialized test to the conformance test suite. It uses a special token (e.g., `WBTEST:`) to push into a new lexer state that then might have different rules vs the rest of the grammar. This would allow for testing different areas of the lexer without having to add more and more rules to the Root state (which might start interacting with each other over time as the number of conformance test cases grow and the rules get more complex).
Opening as a draft to get your feedback on the approach. This demonstrates how the generated lexer currently doesn't support the word boundary `\b` regex properly. (Will next see what might be needed to fix this in the lexer generation.)
This also tweaks …

Fix gen lexer word boundary, case insensitive, and literal matching cases (plus conformance tests)

---

cmd/participle/gen_lexer_cmd.go
lexer/internal/conformance/conformance_test.go

Third time's the charm!
The correct word boundary test when the position is NOT at the beginning and NOT at the end is to always test the character before the current position and the character at the current position.
In the first version, it tested the character at the current position and the next character after the current position.
In the second version, it also tested the character before the current position and the character at the current position.
The correct solution is simpler and makes sense.
Added more conformance tests to cover the changes, including more cases to ensure \b does NOT match when it should not.

More tests and fixes for gen lexer word boundary

---

context.go
lexer/peek.go
lexer/peek_test.go
nodes.go
parser.go

Hi @alecthomas,
when rebasing #213 to master, I decided it would be best to commit my stuff in smaller chunks. The first chunk is some optimizations I did to `PeekingLexer` as it was becoming the bottleneck to the generated parser implementation.
1. **Optimizing `PeekingLexer.Clone` - `Checkpoint`**
It does an allocation that could be avoided. One way is to just have `parseContext` and my generated code to store it by value (keeping pointer receiver for its methods though). This already helps quite a lot, but I went a bit further in my generated code - wrapping the internal cursors in a public `lexer.Checkpoint` type. When a branch needs a backup of the `PeekingLexer` state, it will just need to copy this small struct and restore it only if the branch was *not* accepted and it's even a …

Peeking lexer optimizations

---

_examples/expr2/main.go
_examples/expr2/main_test.go

The expression `1 + false` didn't parse well.
The second `Primary` is empty, as per first commit's tests fails.
Adding a `Boolean` type wrapper to handle it and helps newbies (like me) to start using the library.

Fixes "false" in example/expr2

---

error_test.go
nodes.go

We had an issue using participle when using a structure like the following 
```go
type Union struct {
Float float64 `( @Float` 
String string ` | @String+`
Bool bool     ` | @Boolean )` 
}
```
The code works as intended, but when you use a `@String+` as a part of your union types your error messages get a lot less helpful. Instead of getting errors like 
> 1:1: unexpected token "102"
most of your errors turn into 
> 1:1: sub-expression <string>+ must match at least once
This ends up this way because the group node returns an error when `@Foo+` doesn't match the minimum quantity which then overrides any other useful error reporting and failthroughs 
This small change makes it so that the error is only reported if there is at least one match in a group (and adds a test to enforce it)

avoid returning errors when one-or-more groups have no matches

---

_examples/json/main.go
_examples/json/main_test.go
_examples/json/test.json

feat: json example

---

lexer/simple.go

This addition to `MustSimple` and `NewSimple` docs would help me when writing my lexer. I had to find the answer in https://github.com/alecthomas/participle/discussions/287#discussioncomment-4317476

docs: simple lexer rules are tried in order

---

README.md

The `MustSimple` method accepts the `SimpleRule` slice.

docs: fix GraphQL example

---

scripts/participle
scripts/regen-lexer

It is not required to have `GOBIN` defined, which was a situation I just encountered. 
This fix adds a fallback to use `GOPATH/bin` when `GOBIN` is undefined.
A couple other improvements:
- Use the `go install -C CWD` command-line flag to build from `CWD` instead of using a subshell `(cd CWD; go install ...)`.
- Use paths relative to the `regen-lexer` script for resolving both the neighboring `participle` script and the input/output files.
- This allows `regen-lexer` to be called from _any_ directory (not just the project root).

fix(scripts): add GOBIN fallback and support any cwd
